### ISSUE TITLE
Codefresh runner monitor fails to start

### ISSUE THREAD

**Issue by todaywasawesome** [codefresh-io/cli#523]
```
kubectl logs monitor-57b6c5cc86-m2cnp -n codefresh                         513ms  Tue Jun 30 11:46:49 2020
yarn run v1.19.1
$ node ./src/index.js
Using newrelic: {"config":{"app_name":["cf-k8s-agent[kubernetes]"],"logging":{"level":"info"},"error_collector":{"ignore_status_codes":["400-600"]}}}
Tue, 30 Jun 2020 17:46:21 GMT kubernetes-client deprecated Request() without a .kubeconfig option, see https://github.com/godaddy/kubernetes-client/blob/master/merging-with-kubernetes.md at node_modules/@codefresh-io/kube-integration/lib/kube-client-wrapper/KubeWrapper.js:11:25
New Relic for Node.js halted startup due to an error:
Error: Not starting without license key!
    at cb_nextTick (/cf-k8s-agent/node_modules/newrelic/lib/agent.js:150:16)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
2020-06-30T17:46:21.909Z info: Running step with helm3=false support
GET /api/ping 200 2.191 ms - -
GET /api/ping 200 0.562 ms - -
GET /api/ping 200 0.464 ms - -
GET /api/ping 200 0.429 ms - -
GET /api/ping 200 0.322 ms - -
GET /api/ping 200 0.307 ms - -
```

**Comment by todaywasawesome** [comment]
I deleted the pod and it started fine.

**Comment by oren-codefresh** [comment]
@pasha-codefresh

**Comment by pasha-codefresh** [comment]
this issue not affect monitor, it is just missed new relic key. we had infra issue on our server that actually fixed
