### ISSUE TITLE
[run pipeline] running pipeline throw error 

### ISSUE THREAD

**Issue by verchol** [codefresh-io/cli#63]
cf run 5a3c081091dbe100015e5379
nhandledRejection StatusCodeError: 400 - "Error: Error while trying to fetch commits, incorrect branch / revision, "
    at new StatusCodeError (/Users/codefresh/.nvm/versions/node/v8.0.0/lib/node_modules/codefresh/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/codefresh/.nvm/versions/node/v8.0.0/lib/node_modules/codefresh/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/codefresh/.nvm/versions/node/v8.0.0/lib/node_modules/codefresh/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/codefresh/.nvm/versions/node/v8.0.0/lib/node_modules/codefresh/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/Users/codefresh/.nvm/versions/node/v8.0.0/lib/node_modules/codefresh/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/Users/codefresh/.nvm/versions/node/v8.0.0/lib/node_modules/codefresh/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:312:19)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by itai-codefresh** [comment]
You must pass the branch flag.
Will fux thrown error

**Comment by verchol** [comment]
![image](https://user-images.githubusercontent.com/359038/34616007-706a0442-f23f-11e7-9acc-f5dcf638fe23.png)

**Comment by verchol** [comment]
not mentined branch, and we should have default

**Comment by itai-codefresh** [comment]
Will fix error and run default branch
